"""initial schema

Revision ID: 634b0129cf61
Revises: 
Create Date: 2026-10-04 23:28:50.570390

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '634b0129cf61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_paths',
    sa.Column('flag_id', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('branch_condition', sa.String(length=512), nullable=False),
    sa.Column('reachable_state', sa.Integer(), nullable=False),
    sa.Column('dead_code_lines', sa.JSON(), nullable=False),
    sa.Column('dead_code_snippet', sa.Text(), nullable=False),
    sa.Column('complexity_reduction_score', sa.Integer(), nullable=False),
    sa.Column('true_branch', sa.Text(), nullable=False),
    sa.Column('false_branch', sa.Text(), nullable=False),
    sa.Column('functions_involved', sa.JSON(), nullable=False),
    sa.Column('coverage_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_paths_flag_id'), 'code_paths', ['flag_id'], unique=False)
    op.create_table('code_references',
    sa.Column('flag_id', sa.String(length=64), nullable=False),
    sa.Column('flag_name', sa.String(length=256), nullable=False),
    sa.Column('repository_id', sa.String(length=64), nullable=False),
    sa.Column('repository_name', sa.String(length=256), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('column_number', sa.Integer(), nullable=False),
    sa.Column('code_snippet', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=False),
    sa.Column('is_enclosing_control_flow', sa.Integer(), nullable=False),
    sa.Column('ast_node_type', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_references_flag_id'), 'code_references', ['flag_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('flag_id', sa.String(length=64), nullable=False),
    sa.Column('flag_name', sa.String(length=256), nullable=False),
    sa.Column('repository_name', sa.String(length=256), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_flag_id'), 'evidence_records', ['flag_id'], unique=False)
    op.create_table('removal_operations',
    sa.Column('flag_id', sa.String(length=64), nullable=False),
    sa.Column('flag_name', sa.String(length=256), nullable=False),
    sa.Column('repository_id', sa.String(length=64), nullable=False),
    sa.Column('repository_name', sa.String(length=256), nullable=False),
    sa.Column('target_branch', sa.String(length=128), nullable=False),
    sa.Column('pr_url', sa.String(length=1024), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tool_target', sa.String(length=32), nullable=False),
    sa.Column('files_affected', sa.Integer(), nullable=False),
    sa.Column('lines_removed', sa.Integer(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.String(length=64), nullable=False),
    sa.Column('executed_by', sa.String(length=256), nullable=False),
    sa.Column('diff_summary', sa.Text(), nullable=False),
    sa.Column('safety_branch', sa.String(length=256), nullable=False),
    sa.Column('base_commit', sa.String(length=128), nullable=False),
    sa.Column('stdout_log', sa.Text(), nullable=False),
    sa.Column('stderr_log', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_removal_operations_flag_id'), 'removal_operations', ['flag_id'], unique=False)
    op.create_index(op.f('ix_removal_operations_status'), 'removal_operations', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.String(length=64), nullable=False),
    sa.Column('repository_id', sa.String(length=64), nullable=False),
    sa.Column('repository_name', sa.String(length=256), nullable=False),
    sa.Column('total_scanned_flags', sa.Integer(), nullable=False),
    sa.Column('stale_flags_identified', sa.Integer(), nullable=False),
    sa.Column('removal_operations_completed', sa.Integer(), nullable=False),
    sa.Column('tech_debt_reduction_hours', sa.Integer(), nullable=False),
    sa.Column('code_lines_eliminated', sa.Integer(), nullable=False),
    sa.Column('download_format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repositories',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('local_path', sa.String(length=1024), nullable=False),
    sa.Column('default_branch', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=128), nullable=False),
    sa.Column('scan_status', sa.String(length=32), nullable=False),
    sa.Column('last_scanned_at', sa.String(length=64), nullable=False),
    sa.Column('total_flags', sa.Integer(), nullable=False),
    sa.Column('active_flags', sa.Integer(), nullable=False),
    sa.Column('stale_flags', sa.Integer(), nullable=False),
    sa.Column('potentially_stale_flags', sa.Integer(), nullable=False),
    sa.Column('lines_of_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=False)
    op.create_index(op.f('ix_repositories_scan_status'), 'repositories', ['scan_status'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('flag_id', sa.String(length=64), nullable=False),
    sa.Column('flag_name', sa.String(length=256), nullable=False),
    sa.Column('overall_risk', sa.String(length=32), nullable=False),
    sa.Column('blast_radius_score', sa.Integer(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('assessed_at', sa.String(length=64), nullable=False),
    sa.Column('estimated_cleanup_hours', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_flag_id'), 'risk_assessments', ['flag_id'], unique=False)
    op.create_table('test_runs',
    sa.Column('operation_id', sa.String(length=64), nullable=False),
    sa.Column('repository_id', sa.String(length=64), nullable=False),
    sa.Column('command', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('test_count', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.JSON(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('branch_coverage', sa.String(length=64), nullable=False),
    sa.Column('line_coverage', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_operation_id'), 'test_runs', ['operation_id'], unique=False)
    op.create_table('verification_results',
    sa.Column('operation_id', sa.String(length=64), nullable=False),
    sa.Column('flag_id', sa.String(length=64), nullable=False),
    sa.Column('flag_name', sa.String(length=256), nullable=False),
    sa.Column('repository_name', sa.String(length=256), nullable=False),
    sa.Column('test_suite_status', sa.String(length=32), nullable=False),
    sa.Column('build_status', sa.String(length=32), nullable=False),
    sa.Column('ast_validation_status', sa.String(length=32), nullable=False),
    sa.Column('dead_code_eliminated', sa.Integer(), nullable=False),
    sa.Column('syntax_valid', sa.Integer(), nullable=False),
    sa.Column('regression_detected', sa.Integer(), nullable=False),
    sa.Column('unresolved_references', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('test_output_summary', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_operation_id'), 'verification_results', ['operation_id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.String(length=64), nullable=False),
    sa.Column('repository_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk', sa.String(length=32), nullable=False),
    sa.Column('flag_type', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=False),
    sa.Column('owner_team', sa.String(length=256), nullable=False),
    sa.Column('created_at_flag', sa.String(length=64), nullable=False),
    sa.Column('last_modified', sa.String(length=64), nullable=False),
    sa.Column('stale_since', sa.String(length=64), nullable=False),
    sa.Column('evaluations_count', sa.Integer(), nullable=False),
    sa.Column('evaluations_last_7d', sa.Integer(), nullable=False),
    sa.Column('days_inactive', sa.Integer(), nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('default_value', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=False)
    op.create_index(op.f('ix_feature_flags_repository_id'), 'feature_flags', ['repository_id'], unique=False)
    op.create_index(op.f('ix_feature_flags_status'), 'feature_flags', ['status'], unique=False)
    op.create_table('risk_factors',
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_factors_assessment_id'), 'risk_factors', ['assessment_id'], unique=False)
    op.create_table('scans',
    sa.Column('repository_id', sa.String(length=64), nullable=False),
    sa.Column('repository_name', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_flags_detected', sa.Integer(), nullable=False),
    sa.Column('stale_flags_detected', sa.Integer(), nullable=False),
    sa.Column('scanner_engine', sa.String(length=64), nullable=False),
    sa.Column('scan_duration_ms', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=128), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_repository_id'), 'scans', ['repository_id'], unique=False)
    op.create_table('scan_findings',
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('flag_key', sa.String(length=256), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('ast_node_type', sa.String(length=128), nullable=False),
    sa.Column('is_stale', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_findings_flag_key'), 'scan_findings', ['flag_key'], unique=False)
    op.create_index(op.f('ix_scan_findings_scan_id'), 'scan_findings', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_findings_scan_id'), table_name='scan_findings')
    op.drop_index(op.f('ix_scan_findings_flag_key'), table_name='scan_findings')
    op.drop_table('scan_findings')
    op.drop_index(op.f('ix_scans_repository_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_risk_factors_assessment_id'), table_name='risk_factors')
    op.drop_table('risk_factors')
    op.drop_index(op.f('ix_feature_flags_status'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_repository_id'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_verification_results_operation_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_test_runs_operation_id'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_risk_assessments_flag_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_repositories_scan_status'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('reports')
    op.drop_index(op.f('ix_removal_operations_status'), table_name='removal_operations')
    op.drop_index(op.f('ix_removal_operations_flag_id'), table_name='removal_operations')
    op.drop_table('removal_operations')
    op.drop_index(op.f('ix_evidence_records_flag_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_code_references_flag_id'), table_name='code_references')
    op.drop_table('code_references')
    op.drop_index(op.f('ix_code_paths_flag_id'), table_name='code_paths')
    op.drop_table('code_paths')
    # ### end Alembic commands ###
